function stabilizator(vi,r,rl,vz,tip_dioda,iznom)

f=10000;
T=1/f;
w=2*pi*f;
t=0:T/25:4*T;


Fig=figure('Name','Parametric Voltage Stabilizer',...
 'Units','normalized',...
 'Position',[0.1 0.1 0.8 0.7],...
 'NumberTitle','off','color','#EDB120')

EditGroup=uibuttongroup('Visible','on',...
 'BackgroundColor',[0 0 1],...
'ForegroundColor','black',...
 'Title','Introduced values',...
 'FontSize',10,...
 'FontWeight','bold',...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.05 0.52 0.15 0.4]); 
Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.8 0.25 0.15],...
 'String','Vi[V]',...
 'FontSize',15,...
 'Parent',EditGroup);
Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.6 0.25 0.15],...
 'String','R[Ω]',...
 'FontSize',15,...
 'Parent',EditGroup);
Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.4 0.25 0.15],...
 'String','RL[Ω]',...
 'FontSize',15,...
 'Parent',EditGroup);
Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.2 0.25 0.15],...
 'String','Type of diode',...
 'FontSize',10,...
 'Parent',EditGroup);
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.5 0.8 0.25 0.15],...
 'String',num2str(vi),...
 'Callback','vi=str2num(get(gco,''String''));close;stabilizator(vi,r,rl,vz,tip_dioda,iznom);',...
 'Parent',EditGroup);
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.5 0.6 0.25 0.15],...
 'String',num2str(r),...
 'Callback','r=str2num(get(gco,''String''));close;stabilizator(vi,r,rl,vz,tip_dioda,iznom);',...
 'Parent',EditGroup);
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.5 0.4 0.25 0.15],...
 'String',num2str(rl),...
 'Callback','rl=str2num(get(gco,''String''));close;stabilizator(vi,r,rl,vz,tip_dioda,iznom);',...
 'Parent',EditGroup);
Bp=uicontrol('Style','PopupMenu',...
 'Units','normalized',...
 'Position',[0.5 0.10 0.25 0.25],...
 'value',tip_dioda,...
 'String','1|2|3|4',...
 'Callback','tip_dioda=get(gco,''value'');close;stabilizator(vi,r,rl,vz,tip_dioda,iznom);',...
 'Parent',EditGroup);

x = imread('stabilizator_tensiune.PNG');
imshow(x);
set(gca,'Position',[0.23 0.52 0.4 0.4]);
title('Parametric Voltage Stabilizer');

switch tip_dioda
    case 1
       tip_dioda=2;
    case 2
        tip_dioda=3;
    case 3
        tip_dioda=4;
    case 4
        tip_dioda=5;
end        
  
if tip_dioda==2
    vz=3.3;
    iznom=0.076;
elseif tip_dioda==3
    vz=4.7;
    iznom=0.053;
elseif tip_dioda==4
    vz=5.1;
    iznom=0.049;
elseif tip_dioda==5
    vz=7.5;
    iznom=0.034;
end

if vi<vz
 Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.85 0.15 0.1 0.07],...
 'String','The diode is not correctly polarized.',...
 'FontSize',13);
end

if vz==3.3
 Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.85 0.05 0.1 0.05],...
 'String','Diode is 1N4728A',...
 'FontSize',13);
elseif vz==4.7
  Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.85 0.05 0.1 0.05],...
 'String','Diode is 1N4732A',...
 'FontSize',13);
elseif vz==5.1
   Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.85 0.05 0.1 0.05],...
 'String','Diode is 1N4733A',...
 'FontSize',13);
elseif vz==7.5
  Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.85 0.05 0.1 0.05],...
 'String','Diode is 1N4737A',...
 'FontSize',13);
end

io=((vi-vz)/r)-iznom;
vr=vi-vz;
ir=(vr/r);
vo=io*rl;
vout=vi*sin(w.*t);
ir1=ir*sin(w.*t);
if vo>1000
    vo=(io*rl)*0.0001;
end

if vo<0
  Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.85 0.13 0.1 0.05],...
 'String','The circuit is not powered correctly.',...
 'FontSize',13);
end

EditGroup=uibuttongroup('Visible','on',...
 'BackgroundColor',[0 0 1],...
'ForegroundColor','black',...
 'Title','Result Values',...
 'FontSize',10,...
 'FontWeight','bold',...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.05 0.1 0.15 0.4]); 
Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.8 0.25 0.15],...
 'String','Io[A]',...
 'FontSize',13,...
 'Parent',EditGroup);
Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.6 0.25 0.15],...
 'String','Iz[mA]',...
 'FontSize',14,...
 'Parent',EditGroup);
Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.4 0.25 0.15],...
 'String','Ir[mA]',...
 'FontSize',15,...
 'Parent',EditGroup);
Bp=uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.1 0.2 0.25 0.15],...
 'String','Vo[V]',...
 'FontSize',15,...
 'Parent',EditGroup);
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.5 0.8 0.25 0.15],...
 'String',io,...
 'Callback','io=str2num(get(gco,''String''));close;stabilizator(vi,r,rl,vz,tip_dioda,iznom);',...
 'Parent',EditGroup);
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.5 0.6 0.25 0.15],...
 'String',num2str(iznom),...
 'Callback','iznom=str2num(get(gco,''String''));close;stabilizator(vi,r,rl,vz,tip_dioda,iznom);',...
 'Parent',EditGroup);
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.5 0.4 0.25 0.15],...
 'String',num2str(ir),...
 'Callback','ir=str2num(get(gco,''String''));close;stabilizator(vi,r,rl,vz,tip_dioda,iznom);',...
 'Parent',EditGroup);
Be=uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.5 0.2 0.25 0.15],...
 'String',num2str(vo),...
 'Callback','vo=str2num(get(gco,''String''));close;stabilizator(vi,r,rl,vz,tip_dioda,iznom);',...
 'Parent',EditGroup);

subplot('Position',[0.7 0.65 0.23 0.23])
plot(t,vout);
grid on;
title('Input');
xlabel('Time [s]');
ylabel('Input voltage [Vi]')

iznom1=vo*ones(1, length(t));
subplot('Position',[0.7 0.35 0.23 0.23])
plot(t,iznom1);
grid on;
title('Output');
xlabel('Time [s]');
ylabel('Output voltage [Vo]')

io1=((vi-vz)./rl)-iznom;

subplot('Position',[0.3 0.2 0.23 0.23])
plot(t,ir1);
grid on;
title('Current through the resistor');
xlabel('Time [s]');
ylabel('Current through the resistor [Ir]')

wordDocPDF = 'Documentation.pdf';

f = uicontrol('Style', 'pushbutton', 'String', 'DOCUMENTATION', ...
    'Units', 'normalized', 'Position', [0.85 0.20 0.1 0.05], ...
    'BackgroundColor','[1 1 1]',...
    'Callback', ['winopen("' wordDocPDF '")']);

